version: '3'
services: 
  ########## Rails App ###########
  tcf: 
    build: .
    command: bash -c "yarn install && rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    container_name: tcf
    volumes: 
      - .:/tcf
    tty: true
    ports: 
      - "3000:3000"
    links: 
      - db
    depends_on: 
      - db
  db:
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: data
      MYSQL_DATABASE: thecourseforum_development
    volumes: 
      - ./sql/thecourseforum_development.sql:/docker-entrypoint-initdb.d/thecourseforum_development.sql
    container_name: tcf_database_development
    command: --default-authentication-plugin=mysql_native_password

  ########## Grades Microservice ###########
  grades_api:
    build: ./grades
    restart: always
    ports:
      - "5000:80"
    links:
      - grades_db
    depends_on:
      - grades_db
    container_name: grades_api
    volumes: 
       - ./grades/main.py:/app/main.py
       - ./grades/data:/app/data
    # comment out following line for production
    command: bash -c "python /app/data/load_grades.py /app/data/grades.json && python /app/main.py"


  grades_db:
    image: redislabs/rejson:latest
    container_name: grades_db
    ports:
      - "6379:6379"


    