version: '3'
services: 

  ########## Rails App ###########
  tcf:
    build:
      dockerfile: ./passenger/Dockerfile
      context: .
    container_name: tcf
    restart: unless-stopped
    links: 
      - db
      - grades_api
    depends_on: 
      - db
      - grades_api
  db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: tcf_database

  ########## Grades Microservice ###########
  grades_api:
    build: ./grades
    restart: always
    links:
      - grades_db
    depends_on:
      - grades_db
    container_name: grades_api

  grades_db:
    image: redislabs/rejson:latest
    container_name: grades_db