# a development specific docker-compose file that adds additional config
# to docker-compose.yml and will be run automatically on `docker-compose up`


version: '3'
services: 

  ########## Rails App ###########
  tcf:
    ports:
      - "3000:80"
    volumes:
      - ./passenger/nginx/development.conf:/etc/nginx/sites-enabled/default.conf
      - .:/home/app/theCourseForum
    container_name: tcf_dev
  db:
    environment: 
      MYSQL_ROOT_PASSWORD: data
      MYSQL_DATABASE: thecourseforum_development
    volumes: 
      - ./sql/thecourseforum_development.sql:/docker-entrypoint-initdb.d/thecourseforum_development.sql
    container_name: tcf_database_dev

  ########## Grades Microservice ###########
  grades_api:
    ports:
      - "5000:80"
    volumes: 
       - ./grades/main.py:/app/main.py
       - ./grades/data:/app/data
    # comment out following line for production
    command: bash -c "python /app/data/load_grades.py /app/data/grades.json && python /app/main.py"
    container_name: grades_api_dev
  grades_db:
    container_name: grades_db_dev