version: '3'
services: 
  tcf: 
    build: .
    command: bash -c ' service mysql start && rails s -b 0.0.0.0'
    container_name: tcf
    volumes: 
      - .:/tcf
    tty: true
    ports: 
      - "3000:3000"